spring:
  application:
    name: coffee-shop

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/coffee_shop?serverTimezone=UTC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
outbox:
  enabled: ${OUTBOX_ENABLED:false}
  url: ${ORDER_COLLECTOR_URL:http://localhost:9090/orders}
  batch-size: 10
  retry-delay-seconds: 5
  lease-seconds: 60
  request-timeout-millis: 2000
  poll-delay-ms: 1000
  poll-initial-delay-ms: 1000
